### ISSUE TITLE
[Example][ADD-FRIENDS]: Rayminn

### ISSUE THREAD

**Issue by Rayminn** [FrederickBun/friends#1]
### 交换友链检查清单

- [X] 已经阅读 `README.md`
- [X] 您的站点类型为 `博客`
- [X] [网站域名符合规定](https://github.com/FrederickAsYou/friends/tree/main?tab=readme-ov-file#%E4%BA%A4%E6%8D%A2%E5%89%8D%E8%AF%B7%E9%98%85%E8%AF%BB)
- [X] 网站内容符合国家规定

### 站点名称

Rayminn

### 站点logo

https://avatars.githubusercontent.com/u/98998872/

### 站点URL

https://blog.rayminn.top/

### 站点介绍或人生格言

怀揣理想，拥抱时代

### 站点友链地址

https://blog.rayminn.top/links/

**Comment by FrederickAsYou** [comment]
已添加：预计48小时内生效
